# Generated by Django 5.0.6 on 2024-05-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='node',
            name='label',
            field=models.CharField(max_length=200),
        ),
    ]
