# Generated by Django 5.0.6 on 2024-05-30 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_jsonfile_node_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='json_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='myapp.jsonfile'),
            preserve_default=False,
        ),
    ]
