# Generated by Django 5.0.6 on 2024-06-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_edge_json_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.node')),
            ],
        ),
    ]
