# Generated by Django 5.0.6 on 2024-06-19 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_imagenode_image1_remove_imagenode_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenode',
            name='name',
            field=models.CharField(default='Cerveau', max_length=50),
        ),
        migrations.AlterField(
            model_name='node',
            name='image_node',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nodes', to='myapp.imagenode'),
        ),
    ]
